### ISSUE TITLE
Weather issue

### ISSUE THREAD

**Issue by alexrojco** [husa/e-clock#1]
The weather forecast doesn't work since a couple of days now. I'm no master at chrome/chrome's extensions/JavaScript, so all my pathetic tries to find ping the forecast's source were unsuccessful. I hope you still support this extension because it's by far my most favorite. 

![image](https://user-images.githubusercontent.com/20784378/50743553-67512700-11e7-11e9-8dcc-2e2d3fb2e88b.png)

**Comment by husa** [comment]
Hi @alexrojco 
Thanks for reporting. There's issue with current weather provider, it changed endpoints and terms of use. I'm troubleshooting the issue right now.
